# ===================================================================
# 운영 환경 전용 설정 (application-production.yml)
# ===================================================================

server:
  port: ${SERVER_PORT:8080} # 기본 포트는 8080

spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      password: ${REDISPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update   # 공모전용 → update 허용
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${OAUTH_BACKEND_CALLBACK_URI}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    com.example.moneyway: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO

jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET_KEY}

tourapi:
  service-key: ${TOUR_API_KEY}

OPENAI:
  API:
    KEY: ${OPENAI_API_KEY}

cookie:
  secure: ${COOKIE_SECURE:true}

oauth:
  default-redirect-uri: ${OAUTH_FRONTEND_REDIRECT_URI}
