spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:production}  # local or production (기본은 local, Railway에선 환경변수 설정)

jpa:
  hibernate:
    ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
