spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 기본은 local, Railway에선 환경변수로 production 설정

# (선택사항) 공통 설정이 있다면 여기에 작성
# 예: actuator, 로깅 기본값 등

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO