#application.yml
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # local or production (기본은 local, Railway에선 환경변수 설정)
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false